### PR TITLE
check if ranking is allowed rather than using unacceptable default

### LINKED ISSUE #766: [2.0-RC] Auto-Loading candidates fails when 'Maximum Number of Candidates That Can Be Ranked' setting is set to 'Maximum'
RCTab v 1.4.0
Using the test_data `clear_ballot_kansas_primary`
Config: [clear ballot kansas primary test.json](https://github.com/BrightSpots/rcv/files/13252204/clear.ballot.kansas.primary.test.json)

**What happened:** RCTab failed to auto-load candidates until I unchecked 'Max' checkbox for 'Maximum Number of Candidates that can be ranked' Winning Rules setting. 
**What I would expect to happen:** RCTab would auto-load candidates successfully as long as the CVR was properly configured.

### First Attempt - Not Fully Configured
I configured my contest tab by tab. 
- Set a contest name
- Selected the `clear_ballot_kansas_primary.cvr.csv` file, Contest Id: `Democratic Primary` and added that cvr
- Click Auto-Load and got the following error 
image

### Second Attempt - Fully Configured
I thought maybe I needed to fully configure my contest so I tried again. I configured my contest tab by tab. 
- Set a contest name
- Selected the `clear_ballot_kansas_primary.cvr.csv` file, Contest Id: `Democratic Primary` and added that cvr
- Selected bottoms up with 15% threshold. **Maximum checkbox is checked by default**
image

- always skip to next rank overvote rule
- clicked 'Auto-Load Candidates' and got the same error
```
2023-11-03 12:04:04 EDT INFO: Auto-loading candidates from CVR files...
2023-11-03 12:04:11 EDT SEVERE: Rank: 1 exceeds max rankings allowed in config: 0
2023-11-03 12:04:11 EDT SEVERE: Failed to read source file "/Users/yezr/Downloads/clear ballot kansas primary cvr box id and precinct id swapped.csv": 
2023-11-03 12:04:11 EDT INFO: Auto-loaded 0 candidates.
```

### Third Attempt - Unchecked 'Maximum'
So trying to fix it I went to 'Winning Rules' tab, unchecked 'Max' from the 'Maximum Number of Candidates that can be ranked' setting and changed it to 500. It then successfully loaded all 10 candidates.

### PR DESCRIPTION
**Pull request by artoonie**
Resolves #766 

Auto-loading candidates failed when Max Rankings was set to "Max," because rather than returning a value like INT_MAX, we'd return NumCandidates (which was likely 0).

I think it's best to not return this value at all, but to allow the config to check it directly. In this PR, I replace `getMaxRankingsAllowed()` with `isRankingAllowed(int rank)` throughout.

The only change in functionality is when creating the CVR CSV, and only in the case that the Dominion max ranking is different than the one entered in the config. One test has been updated to match this. (Note: this would have changed anyway when we created the combined CVR CSV in #785.)

For completeness, I also removed the check that ClearBallot was doing that no other reader did (as discussed in #776).

### CODE REVIEW

**Comment by yezr** [comment]
> For completeness, I also removed the check that ClearBallot was doing that no other reader did (as discussed in https://github.com/BrightSpots/rcv/pull/776).

Was this put there because we had some ClearBallot CVRs that showed the invalid behavior this was checking for? It looks like nothing in the tests have that behavior (or else it would trigger an exception with this check in there). But maybe at one time we had a CVR exhibiting that behavior? 

We discussed in #776 we should make sure that if the ClearBallot CVR reader doesn't catch it, that the tabulation does. That almost would be preferred, because then we have the check in the path that all vendors must successfully go through. I can take on the task of trying to create a ClearBallot CVR that does that to confirm that is the case.

**Comment by yezr** [comment]
And #776 was already closed manually, but just confirming that this PR fixes the underlying issue (#766) that #776 was trying to fix

**Comment by artoonie** [comment]
> Was this put there because we had some ClearBallot CVRs that showed the invalid behavior this was checking for? It looks like nothing in the tests have that behavior (or else it would trigger an exception with this check in there). But maybe at one time we had a CVR exhibiting that behavior?

I'm not sure. We only have one clearballot example and it doesn't hit this error.

> We discussed in #776 we should make sure that if the ClearBallot CVR reader doesn't catch it, that the tabulation does. That almost would be preferred, because then we have the check in the path that all vendors must successfully go through. I can take on the task of trying to create a ClearBallot CVR that does that to confirm that is the case.

Perhaps this warrants more discussion -- no other reader throws an error when there are more than the allowed # of votes. A cursory glance indicates that other readers simply ignore any candidate beyond the allowed number of ranks.

I've opted to (1) copy that paradigm, and ignore instead of throwing an error, and (2) check this explicitly in the tabulator in case any reader fails to follow the same paradigm.

Other options:
1. Ensure all readers throw a fatal error when an out-of-bounds rank is provided (instead of silently ignoring)
2. Leave as-is, where only clearballot throws such an error. (Maybe there's a reason for this I don't see?)



> And #776 was already closed manually, but just confirming that this PR fixes the underlying issue (#766) that #776 was trying to fix

Confirmed

**Comment by yezr** [comment]
I don't imagine that a ballot will ever be made that allows a voter to vote for more than what the administrators have determined as their limit. However, I will still add a ticket for us to decide what RCTab should do in that case: automatically limit ballots to the configured maximum or throw a halting exception. 

This is enough to resolve #766 and we can address the above question according to priority.

File: src/main/java/network/brightspots/rcv/BaseCvrReader.java [hunk 1]
```diff
@@ -40,13 +40,21 @@ abstract void readCastVoteRecords(List<CastVoteRecord> castVoteRecords)
...
   public void runAdditionalValidations(List<CastVoteRecord> castVoteRecords)
-      throws CastVoteRecord.CvrParseException {}
+      throws CastVoteRecord.CvrParseException {
+    for (CastVoteRecord cvr : castVoteRecords) {
+      for (Pair<Integer, CandidatesAtRanking> ranking : cvr.candidateRankings) {
+        if (!this.config.isRankingAllowed(ranking.getKey())) {
+          throw new CastVoteRecord.CvrParseException();
+        }
+      }
+    }
```
Comment (tarheel) [inline src/main/java/network/brightspots/rcv/BaseCvrReader.java:56]: is this slow for a large source?

File: src/main/java/network/brightspots/rcv/ResultsWriter.java [hunk 2]
```diff
@@ -624,11 +631,16 @@ String writeGenericCvrCsv(
...
+      BaseCvrReader reader,
+      CvrSource source,
       CSVPrinter csvPrinter,
       CastVoteRecord castVoteRecord)
       throws IOException {
     // for each rank determine what candidate id, overvote, or undervote occurred and print it
     for (int rank = 1; rank <= maxRanks; rank++) {
+      if (!reader.isRankingAllowed(rank, source.getContestId())) {
+        break;
+      }
```
Comment (tarheel) [inline src/main/java/network/brightspots/rcv/ResultsWriter.java:643]: could you clarify which case this is handling?

**Review by tarheel — APPROVED** [review]

**Review by artoonie — COMMENTED** [review]
(I wrote this comment weeks ago but forgot to Submit Review -- submitting now for posterity)
