### PR TITLE
handle unrecognized candidates in CDF

### LINKED ISSUE #453: incorrect overvote label in CDF leads to NPE

### PR DESCRIPTION
**Pull request by tarheel**
Fixes #453 and related problems. We now handle this situation more gracefully.

### CODE REVIEW

File: src/main/java/network/brightspots/rcv/CommonDataFormatReader.java [hunk 1]
```diff
@@ -114,13 +119,15 @@
...
   // parse the given file into a List of CastVoteRecords for tabulation
-  void parseCvrFile(List<CastVoteRecord> castVoteRecords) {
+  void parseCvrFile(List<CastVoteRecord> castVoteRecords) throws UnrecognizedCandidatesException {
     // cvrIndex and fileName are used to generate IDs for cvrs
     int cvrIndex = 0;
     String fileName = new File(filePath).getName();
 
     try {
       HashMap json = JsonParser.readFromFile(filePath, HashMap.class);
+      Map<String, String> candidates = getCandidates();
```
Comment (HEdingfield) [inline src/main/java/network/brightspots/rcv/CommonDataFormatReader.java:129]: Nit: you can just inline this.

Comment (tarheel) [reply src/main/java/network/brightspots/rcv/CommonDataFormatReader.java:129]: That would be very inefficient -- it would mean that we were reloading the whole CVR to get the candidates again for each ballot that we process.

Comment (HEdingfield) [reply src/main/java/network/brightspots/rcv/CommonDataFormatReader.java:129]: Ah, right you are, I missed the loop due to GitHub review line hiding.
