### PR TITLE
fix treatBlankAsUndeclaredWriteIn bugs

### LINKED ISSUE #324: treatBlankAsUndeclaredWriteIn doesn't work

### PR DESCRIPTION
**Pull request by tarheel**
Fixes #324. The key change here is the validation check I added: undeclaredWriteInLabel must be supplied if treatBlankAsUndeclaredWriteIn is true.

### CODE REVIEW

File: src/main/java/network/brightspots/rcv/ContestConfig.java [hunk 1]
```diff
@@ -269,7 +269,10 @@ private void validateTabulatorVersion() {
     } else {
       if (!getTabulatorVersion().equals(Main.APP_VERSION)) {
         isValid = false;
-        Logger.log(Level.SEVERE, "tabulatorVersion %s not supported!.", getTabulatorVersion(),
+        Logger.log(
+            Level.SEVERE,
+            "tabulatorVersion %s not supported!.",
```
Comment (HEdingfield) [inline src/main/java/network/brightspots/rcv/ContestConfig.java]:
```suggestion
            "tabulatorVersion %s not supported!",
```
