### PR TITLE
fix exhausted/inactive counts and remove residual surplus counts in precinct CSVs

### LINKED ISSUE #265: inactive and residual numbers in precinct CSVs are wrong
They're showing the overall totals, not the totals for that precinct.

### PR DESCRIPTION
**Pull request by tarheel**
Fixes #265.

### CODE REVIEW

**Comment by tarheel** [comment]
Yeah, let me rebase before you review this.

**Comment by tarheel** [comment]
OK, I've rebased it.

File: src/main/java/network/brightspots/rcv/ResultsWriter.java [hunk 1]
```diff
@@ -437,7 +443,9 @@ private void generateSummarySpreadsheet(
     // row for residual surplus (if needed)
     // We check if we accumulated any residual surplus over the course of the tabulation by testing
     // whether the value in the final round is positive.
-    if (roundToResidualSurplus.get(numRounds).signum() == 1) {
+    // Note that this concept only makes sense when we're reporting the overall tabulation, so we
+    // omit it when generating results at the individual precinct level.
+    if (precinct == null && roundToResidualSurplus.get(numRounds).signum() == 1) {
```
Comment (moldover) [inline src/main/java/network/brightspots/rcv/ResultsWriter.java]: :+1: for signum usage
