### PR TITLE
Fixes bug that prevents config from loading if no provider is specified.

### LINKED ISSUE #318: Minimal config file fails to load
I thought this was addressed in #296, but, when attempting to load a stripped-down config file with the bare minimum of "required" fields (see an example below), it doesn't properly load for some reason and the error message is entirely unhelpful:

> 2019-06-28 10:22:07 PDT INFO: Successfully loaded contest config: C:\blah\rcv\src\test\resources\network\brightspots\rcv\test_data\sample_interactive_tiebreak\sample_interactive_tiebreak_config.json
> 2019-06-28 10:22:07 PDT SEVERE: Error processing candidate data:
> java.lang.NullPointerException

```
{
  "outputSettings": {
    "contestName": "Sample Interactive Tiebreak",
    "outputDirectory": "output"
  },
  "cvrFileSources": [
    {
      "filePath": "sample_interactive_tiebreak_cvr.xlsx",
      "firstVoteColumnIndex": 2,
      "firstVoteRowIndex": 2
    }
  ],
  "candidates": [
    {
      "name": "Mookie Blaylock"
    },
    {
      "name": "Yinka Dare"
    },
    {
      "name": "George Gervin"
    },
    {
      "name": "Sedale Threatt"
    }
  ],
  "rules": {
    "tiebreakMode": "interactive",
    "overvoteRule": "alwaysSkipToNextRank",
    "maxRankingsAllowed": 3,
    "maxSkippedRanksAllowed": 0,
    "numberOfWinners": 1,
    "decimalPlacesForVoteArithmetic": 4,
    "minimumVoteThreshold": 0
  }
}

```

Assigning to all of us for now, but if you're going to start working on it, please get rid of the other assignees.

### PR DESCRIPTION
**Pull request by HEdingfield**
Fixes #318.

### CODE REVIEW

File: src/main/java/network/brightspots/rcv/ContestConfig.java [hunk 1]
```diff
@@ -222,7 +222,7 @@ private void validateCvrFileSources() {
         }
 
         // perform CDF checks
-        if (source.getProvider().equals("CDF")) {
+        if (source.getProvider() != null && source.getProvider().equals("CDF")) {
```
Comment (tarheel) [inline src/main/java/network/brightspots/rcv/ContestConfig.java]: Maybe we should just have an `isCdf` method on CVRSource?

Comment (HEdingfield) [reply src/main/java/network/brightspots/rcv/ContestConfig.java]: Done.
